### PR TITLE
Match expected package name

### PR DESCRIPTION
**Pull request by LeoColomb**
https://packagist.org/packages/chartisan/php

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
This repo contains an unpublished version that will go live with the next major version of chartisan. We will also change its name sadly!

**Comment by LeoColomb** [comment]
Ok ok, thanks for your answer, no worries 😊
I have to admit current repo statuses are a bit confusing.
This `chartisan/chartisan@4.0.0-beta` PHP package is suppose to be used with `@chartisan/*@4.0.0-beta` npm, right?
And https://github.com/Chartisan/Charts is a totally different usage, correct?

**Comment by ConsoleTVs** [comment]
Chartisan/Charts will be renamed to Chartisan/PHP
This repository will be removed. It currently stores the code that will be added to Chartisan/Charts.

I am sorry for the confusions. I left it half-done.

Regarding versions 4, please DO NOT use them unless you know how to dig into the code to use it. There is no documentation yet, that is what's holding everything down... I need to sit down and write it...

**Comment by ConsoleTVs** [comment]
And yes, the beta pakcages on NPM are compatible with the newest release contained in this repo.

**Pull request closed without merging**
